### ISSUE TITLE
Cart view with checkout option html page--
Add an item to the cart from product listing or product detail pages
Remove an item from the cart
Edit/update quantities of items in the cart
Log in and continue editing the cart
Refresh the page without being logged in and have the cart persist (you may use sessionStorage, localStorage, Cookies or JWT for this)

### ISSUE THREAD

**Issue by colleenpurcell12** [colleenpurcell12/CareFull#14]
Add an item to the cart from product listing or product detail pages
Remove an item from the cart
Edit/update quantities of items in the cart
Log in and continue editing the cart
Refresh the page without being logged in and have the cart persist (you may use sessionStorage, localStorage, Cookies or JWT for this)

**Comment by sharonghae** [comment]
Add item to cart is working
Bugs to fix: When switching users/guest, cart shows previous order, need to rerender current user

Things to do: Edit cart view (add quanity field), Edit quantity, Delete item. Add item to cart button in single product view 

Things to do after cart page is complete: Checkout page! ==> Order History ===> Admin privilege.

Non-priority: Star Reviews
